# Generated by Django 6.1 on 2026-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0003_seed_spanish_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttsvoicesetting',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('pl', 'Polish'), ('es', 'Spanish')], max_length=2),
        ),
    ]
