# Generated by Django 6.1 on 2026-08-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='interface_mode',
            field=models.CharField(choices=[('default', 'Default'), ('preschool', 'Preschool')], default='default', max_length=10),
        ),
    ]
