# Generated by Django 6.1 on 2026-08-20 19:56

import common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_interface_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=common.storage.avatar_image_upload_to)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='equipped_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by', to='accounts.avatar'),
        ),
    ]
