# Generated by Django 6.1 on 2026-08-29 07:23

import common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_avatars'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('clothing', 'Clothing'), ('headwear', 'Headwear'), ('accessory', 'Accessory')], max_length=10)),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=common.storage.avatar_item_image_upload_to)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.avatar')),
            ],
            options={
                'ordering': ['slot', 'order_index', 'id'],
                'unique_together': {('avatar', 'key')},
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='equipped_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_accessory', to='accounts.avataritem'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='equipped_clothing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_clothing', to='accounts.avataritem'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='equipped_headwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_headwear', to='accounts.avataritem'),
        ),
    ]
