# Generated by Django 6.1 on 2026-08-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_reset_steve_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='avataritem',
            name='offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='avataritem',
            name='offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='avataritem',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
    ]
