# Generated by Django 6.1 on 2026-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_avatar_scale_avataritem_offset_x_avataritem_offset_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='equipped_clothing',
        ),
        migrations.AddField(
            model_name='avataritem',
            name='layer_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='equipped_clothing_items',
            field=models.ManyToManyField(blank=True, related_name='equipped_as_clothing_by', to='accounts.avataritem'),
        ),
    ]
