# Generated by Django 6.1 on 2026-08-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_seed_clothing_layer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='avataritem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='unlocked_items',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by', to='accounts.avataritem'),
        ),
    ]
