# Generated by Django 6.1 on 2026-08-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_avataritem_price_studentprofile_unlocked_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='equipped_accessory',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='equipped_headwear',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='equipped_accessory_items',
            field=models.ManyToManyField(blank=True, related_name='equipped_as_accessory_by', to='accounts.avataritem'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='equipped_headwear_items',
            field=models.ManyToManyField(blank=True, related_name='equipped_as_headwear_by', to='accounts.avataritem'),
        ),
    ]
