# Generated by Django 6.1 on 2026-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_steve_costume_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='completed_lessons_percent_cache',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
