# Generated by Django 6.1 on 2026-09-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_kitten_halloween_and_extra_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='translate_on_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='translation_scope',
            field=models.CharField(choices=[('word', 'Word'), ('sentence', 'Sentence')], default='word', max_length=10),
        ),
    ]
