# Generated by Django 6.1 on 2026-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_studentprofile_translate_on_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='translation_scope',
            field=models.CharField(choices=[('off', 'Off'), ('word', 'Word'), ('sentence', 'Sentence')], default='word', max_length=10),
        ),
    ]
