# Generated by Django 6.1 on 2026-09-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_studentprofile_translation_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='interface_mode',
            field=models.CharField(choices=[('default', 'Default'), ('simple', 'Simple'), ('preschool', 'Preschool')], default='default', max_length=10),
        ),
    ]
