# Generated by Django 6.1 on 2026-09-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_studentprofile_interface_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquippedItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.avataritem')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student_profile', 'item')},
            },
        ),
    ]
