# Generated by Django 6.1 on 2026-09-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_equippeditemorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquippedItemPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_x', models.FloatField()),
                ('offset_y', models.FloatField()),
                ('rotation', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.avataritem')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_placements', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student_profile', 'item')},
            },
        ),
    ]
