# Generated by Django 6.1 on 2026-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_equippeditemplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='equippeditemplacement',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
    ]
