# Generated by Django 6.1 on 2026-09-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_crop_avatar_item_padding'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='can_do_any_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
