# Generated by Django 6.1 on 2026-09-02 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_studentprofile_translate_on_select_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('lang', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('pl', 'Polish')], max_length=2)),
                ('translation', models.CharField(max_length=255)),
                ('sample', models.TextField()),
                ('sample_translation', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('known', 'Already know')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_items', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
