# Generated by Django 6.1 on 2026-08-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_studentprofile_school_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(choices=[('with_quiz', 'With quiz'), ('theory', 'Theory'), ('with_task', 'With task')], max_length=10)),
                ('grading_type', models.CharField(choices=[('points', 'Points (1-12)'), ('binary', 'Pass/Fail')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('default_day_offset', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.topic')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('topic', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='lesson_attachments/')),
                ('url', models.URLField(blank=True)),
                ('kind', models.CharField(choices=[('file', 'File'), ('video', 'Video'), ('link', 'Link')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lessons.lesson')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='lessons.lesson')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lessons.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('need_help', 'Need Help'), ('pending_review', 'Pending Review'), ('revision_required', 'Revision Required'), ('completed', 'Completed')], db_index=True, default='assigned', max_length=20)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('is_manually_scheduled', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('grade_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=4, null=True)),
                ('quiz_score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('help_note', models.TextField(blank=True)),
                ('tutor_feedback', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to='accounts.studentprofile')),
                ('subject_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_lessons', to='academics.subjectblock')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='LessonSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='lesson_submissions/')),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('student_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lessons.studentlesson')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLessonStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('need_help', 'Need Help'), ('pending_review', 'Pending Review'), ('revision_required', 'Revision Required'), ('completed', 'Completed')], max_length=20)),
                ('to_status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('need_help', 'Need Help'), ('pending_review', 'Pending Review'), ('revision_required', 'Revision Required'), ('completed', 'Completed')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='lessons.studentlesson')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
