# Generated by Django 6.1 on 2026-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='task_content',
            field=models.TextField(blank=True),
        ),
    ]
