# Generated by Django 6.1 on 2026-08-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_task_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsubmission',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonsubmission',
            name='tutor_feedback',
            field=models.TextField(blank=True),
        ),
    ]
