# Generated by Django 6.1 on 2026-08-20 12:29

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessonsubmission_feedback_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonattachment',
            name='file',
            field=models.FileField(blank=True, upload_to=common.storage.lesson_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='lessonsubmission',
            name='file',
            field=models.FileField(blank=True, upload_to=common.storage.lesson_submission_upload_to),
        ),
    ]
