# Generated by Django 6.1 on 2026-08-20 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessonattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='lessons.lessoncomment'),
        ),
    ]
