# Generated by Django 6.1 on 2026-08-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessoncomment_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlesson',
            name='subject_block',
        ),
    ]
