# Generated by Django 6.1 on 2026-08-20 15:35

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_studentlesson_subject_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='icon',
            field=models.FileField(blank=True, upload_to=common.storage.lesson_icon_upload_to),
        ),
    ]
