# Generated by Django 6.1 on 2026-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_lesson_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizchoice',
            name='text',
            field=models.TextField(),
        ),
    ]
