# Generated by Django 6.1 on 2026-08-21 12:17

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_quizchoice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizchoice',
            name='image',
            field=models.FileField(blank=True, upload_to=common.storage.quiz_choice_image_upload_to),
        ),
    ]
