# Generated by Django 6.1 on 2026-08-24 06:55

import common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_class_class_teacher'),
        ('lessons', '0010_quizchoice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonsJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('json_file', models.FileField(upload_to=common.storage.lessons_json_upload_to)),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed')], default='new', max_length=10)),
                ('lessons', models.ManyToManyField(blank=True, related_name='lessons_json_uploads', to='lessons.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_json_uploads', to='academics.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
