# Generated by Django 6.1 on 2026-08-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lessonsjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsjson',
            name='name',
            field=models.CharField(default='json', max_length=255),
        ),
    ]
