# Generated by Django 6.1 on 2026-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_lessonsjson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('pl', 'Polish')], default='uk', max_length=2),
        ),
    ]
