# Generated by Django 6.1 on 2026-08-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_quizquestion_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsjson',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
