# Generated by Django 6.1 on 2026-08-30 16:30

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_alter_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsubmission',
            name='tutor_feedback_image',
            field=models.FileField(blank=True, upload_to=common.storage.tutor_feedback_image_upload_to),
        ),
    ]
