# Generated by Django 6.1 on 2026-08-30 17:00

import common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_lessonsubmission_tutor_feedback_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=common.storage.lesson_submission_upload_to)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='lessons.lessonsubmission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
