# Generated by Django 6.1 on 2026-08-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_migrate_submission_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsubmission',
            name='file',
        ),
    ]
