# Generated by Django 6.1 on 2026-08-30 18:13

import common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_remove_lessonsubmission_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSubmissionFeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=common.storage.tutor_feedback_image_upload_to)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_feedback_images', to='lessons.lessonsubmission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
