# Generated by Django 6.1 on 2026-08-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_migrate_tutor_feedback_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsubmission',
            name='tutor_feedback_image',
        ),
    ]
