# Generated by Django 6.1 on 2026-09-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_plan'),
        ('accounts', '0020_studentprofile_completed_lessons_percent_cache'),
        ('lessons', '0022_remove_lessonsubmission_tutor_feedback_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCompletionBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_completion_bonuses', to='accounts.studentprofile')),
                ('subject_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_bonuses', to='academics.subjectblock')),
            ],
            options={
                'unique_together': {('student', 'subject_block')},
            },
        ),
        migrations.CreateModel(
            name='TopicCompletionBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_completion_bonuses', to='accounts.studentprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_bonuses', to='academics.topic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
