# Generated by Django 6.1 on 2026-09-02 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0023_semestercompletionbonus_topiccompletionbonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField()),
                ('source_url', models.URLField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('pl', 'Polish')], max_length=2)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lessons.studentlesson')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
