# Generated by Django 6.1 on 2026-09-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_studentlessonmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rectangle', 'Rectangle'), ('ellipse', 'Ellipse'), ('freehand', 'Freehand'), ('text_note', 'Text note'), ('highlight', 'Highlight'), ('comment', 'Comment')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('sentence_start', models.PositiveIntegerField(blank=True, null=True)),
                ('sentence_end', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='lessons.studentlessonmaterial')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
