# Generated by Django 6.1 on 2026-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_materialannotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('pl', 'Polish'), ('es', 'Spanish')], default='uk', max_length=2),
        ),
    ]
