# Generated by Django 6.1 on 2026-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0026_alter_quizquestion_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='synopsis_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
