# Generated by Django 6.1 on 2026-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_lesson_synopsis_studentlesson_synopsis_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlessonmaterial',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('pl', 'Polish'), ('es', 'Spanish')], max_length=2),
        ),
    ]
