# Generated by Django 6.1 on 2026-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_alter_studentlessonmaterial_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='is_self_selected',
            field=models.BooleanField(default=False),
        ),
    ]
