# Generated by Django 6.1 on 2026-09-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0029_studentlesson_is_self_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
