# Generated by Django 6.1 on 2026-09-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0030_studentlesson_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
    ]
