# Generated by Django 6.1 on 2026-09-20 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_subject_and_group_is_marked'),
        ('accounts', '0033_studentprofile_can_do_any_lesson'),
        ('lessons', '0031_lesson_need_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_subjects', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='academics.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
