# Generated by Django 6.1 on 2026-09-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0032_favoritesubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(max_length=11, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_language', models.CharField(blank=True, max_length=20)),
                ('tracks', models.JSONField(blank=True, default=list)),
                ('selected_language', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('youtube', 'YouTube subtitles'), ('youtube_auto', 'YouTube auto-generated subtitles')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='lessons.youtubevideo')),
            ],
            options={
                'unique_together': {('video', 'language_code')},
            },
        ),
    ]
