"use client";

import Script from "next/script";
import { useTranslations } from "next-intl";
import { useRouter } from "@/i18n/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { useAuthStore } from "@school-ahead/api-client";
import { mapApiUserToAuthUser } from "@school-ahead/api-client";
// Generated by `bun run orval:generate` (with the Django backend up) — see
// orval.config.ts's `schoolAheadBrowser` target.
import { useGoogleLogin } from "@school-ahead/api-client/browser/auth/auth";

declare global {
  interface Window {
    google?: {
      accounts: {
        id: {
          initialize: (config: {
            client_id: string;
            callback: (response: { credential: string }) => void;
          }) => void;
          renderButton: (parent: HTMLElement, options: { theme: string; size: string }) => void;
        };
      };
    };
  }
}

export default function LoginPage() {
  const t = useTranslations("Login");
  const router = useRouter();
  const setUser = useAuthStore((state) => state.setUser);
  const [error, setError] = useState(false);
  const buttonContainerRef = useRef<HTMLDivElement>(null);

  const googleLogin = useGoogleLogin();

  const handleCredential = useCallback(
    (response: { credential: string }) => {
      setError(false);
      googleLogin.mutate(
        { data: { id_token: response.credential } },
        {
          onSuccess: (result) => {
            setUser(mapApiUserToAuthUser(result.user));
            router.push("/");
          },
          onError: () => setError(true),
        },
      );
    },
    [googleLogin, setUser, router],
  );

  // handleCredential's identity changes often (React Query recreates the
  // mutation object across renders). Routing through a ref keeps the
  // initialize-on-mount effect below stable — Google's SDK is only ever
  // initialized once per page load, avoiding the button being torn down
  // and re-rendered (and the "initialize() called multiple times" warning)
  // on every unrelated re-render.
  const handleCredentialRef = useRef(handleCredential);
  useEffect(() => {
    handleCredentialRef.current = handleCredential;
  });

  const renderGoogleButton = useCallback(() => {
    if (!window.google || !buttonContainerRef.current) return;

    const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
    if (!clientId) {
      console.error(
        "NEXT_PUBLIC_GOOGLE_CLIENT_ID is not set — the Google sign-in button cannot render. " +
          "See frontend/.env.local.example.",
      );
      return;
    }

    window.google.accounts.id.initialize({
      client_id: clientId,
      callback: (response) => handleCredentialRef.current(response),
    });
    window.google.accounts.id.renderButton(buttonContainerRef.current, {
      theme: "outline",
      size: "large",
    });
  }, []);

  // Handles the case where the gsi/client script was already loaded by a
  // previous navigation (Next.js's <Script onLoad> only fires for a fresh
  // load, not a cached one). Runs once on mount only.
  useEffect(() => {
    renderGoogleButton();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="flex flex-1 items-center justify-center p-8">
      <Script
        src="https://accounts.google.com/gsi/client"
        strategy="afterInteractive"
        onLoad={renderGoogleButton}
      />
      <div className="flex flex-col items-center gap-4 text-center">
        <h1 className="text-2xl font-semibold">{t("title")}</h1>
        <p className="text-sm text-gray-600">{t("subtitle")}</p>
        <div ref={buttonContainerRef} />
        {googleLogin.isPending && <p className="text-sm text-gray-500">{t("signingIn")}</p>}
        {error && <p className="text-sm text-red-600">{t("error")}</p>}
      </div>
    </div>
  );
}
