import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/copy-svgedit-assets.mjs (predev/prebuild) — the
    // svgedit npm package's own dist build, served as static files rather
    // than run through our bundler (see @school-ahead/avatar's
    // SvgArtworkEditor). Third-party build output, not our source.
    "public/svgedit/**",
  ]),
]);

export default eslintConfig;
