# Generated by Django 6.1 on 2026-09-11 16:23

import django.db.models.deletion
from django.db import migrations, models

import common.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0028_equippeditemplacement_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.FileField(blank=True, upload_to=common.storage.story_cover_upload_to)),
                ('content', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='accounts.tutorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to=common.storage.story_asset_upload_to)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='preschool.story')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
