# Generated by Django 6.1 on 2026-09-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preschool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyasset',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
