# Generated by Django 6.1 on 2026-09-11 18:39

import django.core.validators
from django.db import migrations, models

import common.storage


class Migration(migrations.Migration):

    dependencies = [
        ('preschool', '0002_rename_image_storyasset_file_story_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyasset',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storyasset',
            name='file',
            field=models.FileField(upload_to=common.storage.story_asset_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'mp3', 'wav', 'ogg', 'm4a', 'mp4', 'webm', 'mov', 'avi'])]),
        ),
    ]
