# Generated by Django 6.1 on 2026-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preschool', '0003_storyasset_original_filename_alter_storyasset_file'),
    ]

    operations = [
        # unique=True added in a later migration, after the data migration
        # backfills every existing row — adding it here would fail
        # immediately since every existing Story would get slug='' at once.
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, default=''),
        ),
    ]
