# Generated by Django 6.1 on 2026-09-23 09:58

import common.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preschool', '0009_seed_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=common.storage.background_music_upload_to, validators=[django.core.validators.FileExtensionValidator(['mp3', 'ogg', 'wav', 'm4a'])])),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'background music',
                'ordering': ['order', 'id'],
            },
        ),
    ]
