# Generated by Django 6.1 on 2026-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preschool', '0010_background_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('pl', 'Polish'), ('es', 'Spanish')], default='uk', max_length=2),
        ),
    ]
