# Generated by Django 6.1 on 2026-08-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='academics.subjectblock'),
        ),
    ]
