# Generated by Django 6.1 on 2026-08-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject_block_manually_set',
            field=models.BooleanField(default=False),
        ),
    ]
