# Generated by Django 6.1 on 2026-08-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_topic_subject_block_manually_set'),
        ('accounts', '0005_seed_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='accounts.tutorprofile'),
        ),
    ]
