# Generated by Django 6.1 on 2026-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_class_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
