# Generated by Django 6.1 on 2026-08-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subject_is_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
