# Generated by Django 6.1 on 2026-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_backfill_subject_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectblock',
            name='weeks_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectblock',
            name='workload',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
