# Generated by Django 6.1 on 2026-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_backfill_block_dates_and_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectblock',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
