# Generated by Django 6.1 on 2026-09-09 11:37

import common.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=common.storage.subject_material_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.subject')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
