# Generated by Django 6.1 on 2026-09-13 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_subjectmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='attestation_type',
            field=models.CharField(choices=[('none', 'Немає атестації'), ('test', 'Тест'), ('exam', 'Екзамен'), ('project', 'Проект')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='order_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.subjectgroup'),
        ),
    ]
