# Generated by Django 6.1 on 2026-09-18 18:11

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_reorder_subject_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='icon',
            field=models.FileField(blank=True, upload_to=common.storage.subject_group_icon_upload_to),
        ),
    ]
