# Generated by Django 6.1 on 2026-09-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_compress_subject_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
