# Generated by Django 6.1 on 2026-09-20 06:14

from django.db import migrations, models


def mark_existing(apps, schema_editor):
    """The preschool bookshelf's default view shows only what a tutor marked.
    Nothing has been marked yet, so without this the shelf would go empty the
    moment this is deployed — start with everything that exists marked, and
    let a tutor un-mark what should be left out. Anything created later starts
    unmarked."""
    apps.get_model('academics', 'Subject').objects.update(is_marked=True)
    apps.get_model('academics', 'SubjectGroup').objects.update(is_marked=True)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_class_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing, migrations.RunPython.noop),
    ]
