# Generated by Django 6.1 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_subject_and_group_is_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_self_enrollable',
            field=models.BooleanField(default=False),
        ),
    ]
