# Generated by Django 6.1 on 2026-09-22 14:30

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_letter', models.CharField(max_length=4)),
                ('second_part', models.CharField(max_length=4)),
                ('icon', models.FileField(blank=True, upload_to=common.storage.syllable_icon_upload_to)),
                ('language', models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('pl', 'Polish'), ('es', 'Spanish')], default='uk', max_length=2)),
            ],
            options={
                'ordering': ['language', 'first_letter', 'second_part'],
                'unique_together': {('language', 'first_letter', 'second_part')},
            },
        ),
    ]
