# Generated by Django 6.1 on 2026-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllable',
            name='word',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
