# Generated by Django 6.1 on 2026-09-22 14:42

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_syllable_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllable',
            name='audio',
            field=models.FileField(blank=True, upload_to=common.storage.syllable_audio_upload_to),
        ),
    ]
