# Generated by Django 6.1 on 2026-09-22 14:43

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_syllable_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllable',
            old_name='audio',
            new_name='syllable_audio',
        ),
        migrations.AddField(
            model_name='syllable',
            name='word_audio',
            field=models.FileField(blank=True, upload_to=common.storage.word_audio_upload_to),
        ),
    ]
