# Generated by Django 6.1 on 2026-09-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_rename_audio_syllable_syllable_audio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='syllable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='syllable',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='syllable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('language', 'first_letter', 'second_part'), name='reading_syllable_one_default_per_syllable'),
        ),
    ]
