# Generated by Django 6.1 on 2026-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_alter_syllable_unique_together_syllable_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllable',
            name='second_part',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
