# Generated by Django 6.1 on 2026-09-08 09:31

import common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0014_plan'),
        ('accounts', '0028_equippeditemplacement_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('markdown', 'Markdown'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=common.storage.task_image_upload_to)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.topic')),
            ],
            options={
                'ordering': ['topic__order_index', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='accounts.studentprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task')),
            ],
            options={
                'unique_together': {('student', 'task')},
            },
        ),
    ]
