import { useEffect, useSyncExternalStore } from "react";
import { mapApiUserToAuthUser, useAuthStore } from "@school-ahead/api-client";
// Generated by `bun run orval:generate` (with the Django backend up) — see
// orval.config.ts's `schoolAheadBrowser` target.
import { googleLogin } from "@school-ahead/api-client/browser/auth/auth";
import { useRouter } from "@/i18n/navigation";

// Google Identity Services, shared by every sign-in button on the page: the
// header's, the landing page's and the public lesson's (`GoogleSignInButton`). GIS is
// initialised once per page load — a second `initialize()` only logs a warning
// and replaces the first callback — so the credential callback below lives at
// module level and every button just reports its state from here.

declare global {
  interface Window {
    google?: {
      accounts: {
        id: {
          initialize: (config: {
            client_id: string;
            callback: (response: { credential: string }) => void;
          }) => void;
          renderButton: (
            parent: HTMLElement,
            options: { theme?: string; size?: string; width?: number; text?: string },
          ) => void;
        };
      };
    };
  }
}

export type GoogleSignInStatus = "idle" | "pending" | "error";

const SCRIPT_SRC = "https://accounts.google.com/gsi/client";

let status: GoogleSignInStatus = "idle";
const statusListeners = new Set<() => void>();
// One entry per mounted `useGoogleSignIn`; the first one navigates after a
// successful sign-in (they would all do the same thing).
const signedInHandlers = new Set<() => void>();
let scriptPromise: Promise<void> | null = null;
let initialized = false;

function setStatus(next: GoogleSignInStatus) {
  status = next;
  statusListeners.forEach((listener) => listener());
}

function loadScript(): Promise<void> {
  if (window.google?.accounts?.id) return Promise.resolve();
  scriptPromise ??= new Promise<void>((resolve, reject) => {
    const script = document.createElement("script");
    script.src = SCRIPT_SRC;
    script.async = true;
    script.onload = () => resolve();
    script.onerror = () => {
      scriptPromise = null;
      script.remove();
      reject(new Error("Google Identity Services failed to load"));
    };
    document.head.appendChild(script);
  });
  return scriptPromise;
}

async function handleCredential(response: { credential: string }) {
  if (status === "pending") return;
  setStatus("pending");
  try {
    const result = await googleLogin({ id_token: response.credential });
    useAuthStore.getState().setUser(mapApiUserToAuthUser(result.user));
    setStatus("idle");
    signedInHandlers.values().next().value?.();
  } catch {
    setStatus("error");
  }
}

// Draws Google's own sign-in button into `parent`. Resolves to false — and the
// caller keeps whatever fallback it has — when the script can't load or the
// client id isn't configured.
export async function renderGoogleButton(
  parent: HTMLElement,
  options: { theme?: string; size?: string; width?: number },
): Promise<boolean> {
  const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
  if (!clientId) {
    console.error(
      "NEXT_PUBLIC_GOOGLE_CLIENT_ID is not set — the Google sign-in button cannot render. " +
        "See frontend/.env.local.example.",
    );
    return false;
  }
  try {
    await loadScript();
  } catch (error) {
    console.error(error);
    return false;
  }
  const google = window.google;
  if (!google) return false;
  if (!initialized) {
    google.accounts.id.initialize({ client_id: clientId, callback: handleCredential });
    initialized = true;
  }
  google.accounts.id.renderButton(parent, options);
  return true;
}

function subscribe(listener: () => void) {
  statusListeners.add(listener);
  return () => {
    statusListeners.delete(listener);
  };
}

// Where a button reads the sign-in state from, and where it is sent (the home
// page, i.e. the dashboard) once Google's credential has been accepted.
export function useGoogleSignIn(): GoogleSignInStatus {
  const router = useRouter();
  const current = useSyncExternalStore(
    subscribe,
    () => status,
    () => "idle" as const,
  );

  useEffect(() => {
    const handler = () => router.push("/");
    signedInHandlers.add(handler);
    return () => {
      signedInHandlers.delete(handler);
    };
  }, [router]);

  return current;
}

// Test hook: the module state outlives a test file's cases.
export function resetGoogleSignInForTests() {
  status = "idle";
  initialized = false;
  scriptPromise = null;
  statusListeners.clear();
  signedInHandlers.clear();
}
