# Generated by Django 6.1 on 2026-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('min_percent', models.PositiveSmallIntegerField()),
                ('max_percent', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
