# Generated by Django 6.1 on 2026-09-04 21:19

import common.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0028_equippeditemplacement_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(upload_to=common.storage.furniture_model_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj', 'stl'])])),
                ('texture_file', models.FileField(blank=True, null=True, upload_to=common.storage.furniture_texture_upload_to)),
                ('thumbnail_image', models.FileField(upload_to=common.storage.furniture_thumbnail_upload_to)),
                ('price', models.PositiveIntegerField(default=0)),
                ('default_position_x', models.FloatField(default=0.0)),
                ('default_position_y', models.FloatField(default=0.0)),
                ('default_position_z', models.FloatField(default=0.0)),
                ('default_rotation_x', models.FloatField(default=0.0)),
                ('default_rotation_y', models.FloatField(default=0.0)),
                ('default_rotation_z', models.FloatField(default=0.0)),
                ('default_scale', models.FloatField(default=1.0)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FurniturePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='house.furnitureitem')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_purchases', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student_profile', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PlacedFurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('scale', models.FloatField(default=1.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='house.furnitureitem')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_furniture', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student_profile', 'item')},
            },
        ),
    ]
