# Generated by Django 6.1 on 2026-09-05 09:01

import common.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureitem',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to=common.storage.furniture_material_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mtl'])]),
        ),
    ]
