# Generated by Django 6.1 on 2026-09-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_furnitureitem_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureitem',
            name='surface',
            field=models.CharField(choices=[('floor', 'Floor'), ('wall', 'Wall'), ('ceiling', 'Ceiling')], default='floor', max_length=10),
        ),
    ]
