# Generated by Django 6.1 on 2026-09-05 10:01

import pathlib

import common.storage
import django.db.models.deletion
from django.db import migrations, models


def copy_texture_file_to_furniture_texture(apps, schema_editor):
    """Data migration: every FurnitureItem.texture_file becomes its first
    FurnitureTexture row before the old single-texture field is dropped
    below, so existing catalog items keep their texture instead of losing
    it. original_filename is set from the stored (already-randomized —
    see common.storage._unique_path) name, same as any texture uploaded
    before this migration ever had no better name to offer."""
    FurnitureItem = apps.get_model('house', 'FurnitureItem')
    FurnitureTexture = apps.get_model('house', 'FurnitureTexture')
    for item in FurnitureItem.objects.exclude(texture_file='').exclude(texture_file__isnull=True):
        FurnitureTexture.objects.create(
            item=item,
            file=item.texture_file.name,
            original_filename=pathlib.PurePosixPath(item.texture_file.name).name,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_furnitureitem_surface'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=common.storage.furniture_texture_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textures', to='house.furnitureitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(copy_texture_file_to_furniture_texture, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='furnitureitem',
            name='texture_file',
        ),
    ]
