# Generated by Django 6.1 on 2026-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_remove_furnitureitem_texture_file_furnituretexture'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureitem',
            name='kind',
            field=models.CharField(choices=[('normal', 'Normal'), ('with_hole', 'With hole')], default='normal', max_length=10),
        ),
    ]
