# Generated by Django 6.1 on 2026-09-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_furnitureitem_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnitureitem',
            name='kind',
        ),
    ]
