# Generated by Django 6.1 on 2026-09-05 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_equippeditemplacement_scale'),
        ('house', '0006_remove_furnitureitem_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_color', models.CharField(default='#f4efe4', max_length=7)),
                ('floor_color', models.CharField(default='#e7e0d3', max_length=7)),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_style', to='accounts.studentprofile')),
            ],
        ),
    ]
