# Generated by Django 6.1 on 2026-09-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0028_equippeditemplacement_scale'),
        ('lessons', '0028_alter_studentlessonmaterial_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cards', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
