# Generated by Django 6.1 on 2026-09-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_crop_avatar_item_padding'),
        ('cards', '0001_initial'),
        ('lessons', '0028_alter_studentlessonmaterial_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCustomLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentCustomTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_cards', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='studentcard',
            name='custom_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_cards', to='cards.studentcustomlesson'),
        ),
        migrations.AddConstraint(
            model_name='studentcard',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_lesson__isnull', True), ('lesson__isnull', False)), models.Q(('custom_lesson__isnull', False), ('lesson__isnull', True)), _connector='OR'), name='studentcard_exactly_one_lesson_source'),
        ),
        migrations.AddField(
            model_name='studentcustomtopic',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_topics', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentcustomlesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='cards.studentcustomtopic'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcustomtopic',
            unique_together={('student', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcustomlesson',
            unique_together={('topic', 'title')},
        ),
    ]
