# Generated by Django 6.1 on 2026-09-17, hand-adjusted to backfill existing
# StudentCustomTopic rows (created before this migration existed, back when
# it was a direct student->topic bucket with no subject in between) into a
# placeholder StudentCustomSubject rather than losing that FK target — see
# cards/models.py's StudentCustomSubject/StudentCustomTopic docstrings.

import django.db.models.deletion
from django.db import migrations, models


# Matches the untranslated fallback label used elsewhere for "no subject
# name available" — kept as a plain literal here (migrations must stay
# runnable independent of any later i18n/copy change).
PLACEHOLDER_SUBJECT_TITLE = 'Без предмету'


def backfill_subject(apps, schema_editor):
    StudentCustomTopic = apps.get_model('cards', 'StudentCustomTopic')
    StudentCustomSubject = apps.get_model('cards', 'StudentCustomSubject')

    subject_by_student_id = {}
    for topic in StudentCustomTopic.objects.all():
        subject = subject_by_student_id.get(topic.student_id)
        if subject is None:
            subject, _created = StudentCustomSubject.objects.get_or_create(
                student_id=topic.student_id, title=PLACEHOLDER_SUBJECT_TITLE
            )
            subject_by_student_id[topic.student_id] = subject
        topic.subject = subject
        topic.save(update_fields=['subject'])


def noop_reverse(apps, schema_editor):
    # Nothing to reverse into — a reversed migrate drops the subject/student
    # columns' data along with the schema change itself, same as any other
    # irreversible backfill in this codebase.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_crop_avatar_item_padding'),
        ('cards', '0002_studentcustomlesson_studentcustomtopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCustomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='custom_subjects',
                        to='accounts.studentprofile',
                    ),
                ),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('student', 'title')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentcustomtopic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentcustomtopic',
            name='subject',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='topics',
                to='cards.studentcustomsubject',
            ),
        ),
        migrations.RunPython(backfill_subject, noop_reverse),
        migrations.AlterField(
            model_name='studentcustomtopic',
            name='subject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='topics',
                to='cards.studentcustomsubject',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='studentcustomtopic',
            unique_together={('subject', 'title')},
        ),
        migrations.RemoveField(
            model_name='studentcustomtopic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentcustomtopic',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentcustomtopic',
            name='updated_at',
        ),
    ]
